apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":30625,"protocol":"TCP","serviceName":"fh-validation:unit-6","allNodes":true},{"addresses":["10.88.10.101"],"port":31476,"protocol":"TCP","serviceName":"fh-validation:unit-6","allNodes":true},{"addresses":["10.88.10.101"],"port":31529,"protocol":"TCP","serviceName":"fh-validation:unit-6","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-6","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-6","port":1266},{"name":"unit-6-replica1","port":2266},{"name":"unit-6-replica2","port":2267}],"selector":{"app":"unit-6"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T11:25:03Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-6
  namespace: fh-validation
  resourceVersion: "104258209"
  uid: 92e35996-6c74-460f-8442-9123badc33e9
spec:
  clusterIP: 10.43.64.62
  clusterIPs:
  - 10.43.64.62
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-6
    nodePort: 30625
    port: 1266
    protocol: TCP
    targetPort: 1266
  - name: unit-6-replica1
    nodePort: 31476
    port: 2266
    protocol: TCP
    targetPort: 2266
  - name: unit-6-replica2
    nodePort: 31529
    port: 2267
    protocol: TCP
    targetPort: 2267
  selector:
    app: unit-6
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
