apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":32574,"protocol":"TCP","serviceName":"fh-validation:unit-2","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-2","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-2","port":1276}],"selector":{"app":"unit-2"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T11:25:03Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-2
  namespace: fh-validation
  resourceVersion: "104258217"
  uid: 8dc53aaf-805f-4ae1-a2ab-f9b577d8bd12
spec:
  clusterIP: 10.43.156.109
  clusterIPs:
  - 10.43.156.109
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-2
    nodePort: 32574
    port: 1276
    protocol: TCP
    targetPort: 1276
  selector:
    app: unit-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
