apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":32663,"protocol":"TCP","serviceName":"fh-validation:unit-5","allNodes":true},{"addresses":["10.88.10.101"],"port":30094,"protocol":"TCP","serviceName":"fh-validation:unit-5","allNodes":true},{"addresses":["10.88.10.101"],"port":30461,"protocol":"TCP","serviceName":"fh-validation:unit-5","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-5","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-5","port":1229},{"name":"unit-5-replica1","port":2229},{"name":"unit-5-replica2","port":2230}],"selector":{"app":"unit-5"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T11:25:03Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-5
  namespace: fh-validation
  resourceVersion: "104258197"
  uid: 9d56ae75-88e5-443b-b690-fc36c2843c3c
spec:
  clusterIP: 10.43.1.15
  clusterIPs:
  - 10.43.1.15
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-5
    nodePort: 32663
    port: 1229
    protocol: TCP
    targetPort: 1229
  - name: unit-5-replica1
    nodePort: 30094
    port: 2229
    protocol: TCP
    targetPort: 2229
  - name: unit-5-replica2
    nodePort: 30461
    port: 2230
    protocol: TCP
    targetPort: 2230
  selector:
    app: unit-5
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
