apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":32663,"protocol":"TCP","serviceName":"fh-validation:unit-5","allNodes":true},{"addresses":["10.88.10.101"],"port":30094,"protocol":"TCP","serviceName":"fh-validation:unit-5","allNodes":true},{"addresses":["10.88.10.101"],"port":30461,"protocol":"TCP","serviceName":"fh-validation:unit-5","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"unit-5","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-5","namespace":"fh-validation"},"spec":{"selector":{"matchLabels":{"app":"unit-5"}},"template":{"metadata":{"labels":{"app":"unit-5"},"name":"unit-5"},"spec":{"containers":[{"args":["--","--to-execute","unit_5"],"image":"floriheld/sorrir-validation:1b","imagePullPolicy":"Always","name":"unit-5","volumeMounts":[{"mountPath":"/usr/src/sorrir/app/config","name":"config"}]}],"imagePullSecrets":[{"name":"vs-validation"}],"nodeSelector":{"k3s.io/hostname":"desktop-03"},"volumes":[{"configMap":{"items":[{"key":"production.json","path":"production.json"},{"key":"units.json","path":"units.json"},{"key":"setup.json","path":"setup.json"},{"key":"production.sec.json","path":"production.sec.json"}],"name":"unit-5"},"name":"config"}]}}}}
  creationTimestamp: "2022-01-12T11:25:06Z"
  generation: 2
  labels:
    app: unit-5
    app.kubernetes.io/managed-by: pulumi
  name: unit-5
  namespace: fh-validation
  resourceVersion: "104258375"
  uid: 150eceb2-bfe4-4a67-a072-3a82ae462d8b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: unit-5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unit-5
      name: unit-5
    spec:
      containers:
      - args:
        - --
        - --to-execute
        - unit_5
        image: floriheld/sorrir-validation:1b
        imagePullPolicy: Always
        name: unit-5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/sorrir/app/config
          name: config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: vs-validation
      nodeSelector:
        k3s.io/hostname: desktop-03
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: production.json
            path: production.json
          - key: units.json
            path: units.json
          - key: setup.json
            path: setup.json
          - key: production.sec.json
            path: production.sec.json
          name: unit-5
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-12T11:25:21Z"
    lastUpdateTime: "2022-01-12T11:25:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-12T11:25:06Z"
    lastUpdateTime: "2022-01-12T11:25:21Z"
    message: ReplicaSet "unit-5-7498495b86" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
