apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":30727,"protocol":"TCP","serviceName":"fh-validation:unit-3","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"unit-3","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-3","namespace":"fh-validation"},"spec":{"selector":{"matchLabels":{"app":"unit-3"}},"template":{"metadata":{"labels":{"app":"unit-3"},"name":"unit-3"},"spec":{"containers":[{"args":["--","--to-execute","unit_3"],"image":"floriheld/sorrir-validation:1c","imagePullPolicy":"Always","name":"unit-3","volumeMounts":[{"mountPath":"/usr/src/sorrir/app/config","name":"config"}]}],"imagePullSecrets":[{"name":"vs-validation"}],"nodeSelector":{"k3s.io/hostname":"desktop-01"},"volumes":[{"configMap":{"items":[{"key":"production.json","path":"production.json"},{"key":"units.json","path":"units.json"},{"key":"setup.json","path":"setup.json"},{"key":"production.sec.json","path":"production.sec.json"}],"name":"unit-3"},"name":"config"}]}}}}
  creationTimestamp: "2022-01-12T11:39:17Z"
  generation: 2
  labels:
    app: unit-3
    app.kubernetes.io/managed-by: pulumi
  name: unit-3
  namespace: fh-validation
  resourceVersion: "104261159"
  uid: d5aa79f0-f9f3-402c-ba71-e39b600aa08b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: unit-3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unit-3
      name: unit-3
    spec:
      containers:
      - args:
        - --
        - --to-execute
        - unit_3
        image: floriheld/sorrir-validation:1c
        imagePullPolicy: Always
        name: unit-3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/sorrir/app/config
          name: config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: vs-validation
      nodeSelector:
        k3s.io/hostname: desktop-01
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: production.json
            path: production.json
          - key: units.json
            path: units.json
          - key: setup.json
            path: setup.json
          - key: production.sec.json
            path: production.sec.json
          name: unit-3
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-12T11:39:35Z"
    lastUpdateTime: "2022-01-12T11:39:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-12T11:39:17Z"
    lastUpdateTime: "2022-01-12T11:39:35Z"
    message: ReplicaSet "unit-3-6ff8f76b6c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
