apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":31271,"protocol":"TCP","serviceName":"fh-validation:unit-2","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-2","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-2","port":1270}],"selector":{"app":"unit-2"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T11:39:16Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-2
  namespace: fh-validation
  resourceVersion: "104261050"
  uid: c4e8cb5a-37c4-4329-974b-cbbaa0e69bce
spec:
  clusterIP: 10.43.219.29
  clusterIPs:
  - 10.43.219.29
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-2
    nodePort: 31271
    port: 1270
    protocol: TCP
    targetPort: 1270
  selector:
    app: unit-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
