apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":30727,"protocol":"TCP","serviceName":"fh-validation:unit-3","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-3","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-3","port":1290}],"selector":{"app":"unit-3"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T11:39:16Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-3
  namespace: fh-validation
  resourceVersion: "104261057"
  uid: 4e459554-6bc5-40e4-ac95-d32932bbbf83
spec:
  clusterIP: 10.43.85.64
  clusterIPs:
  - 10.43.85.64
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-3
    nodePort: 30727
    port: 1290
    protocol: TCP
    targetPort: 1290
  selector:
    app: unit-3
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
