apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":30890,"protocol":"TCP","serviceName":"fh-validation:unit-3","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-3","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-3","port":1258}],"selector":{"app":"unit-3"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T11:54:12Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-3
  namespace: fh-validation
  resourceVersion: "104263893"
  uid: 899fc914-84a1-4fa7-8dda-e3c02041bcac
spec:
  clusterIP: 10.43.241.181
  clusterIPs:
  - 10.43.241.181
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-3
    nodePort: 30890
    port: 1258
    protocol: TCP
    targetPort: 1258
  selector:
    app: unit-3
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
