apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":31393,"protocol":"TCP","serviceName":"fh-validation:unit-2","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-2","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-2","port":1248}],"selector":{"app":"unit-2"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T12:16:52Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-2
  namespace: fh-validation
  resourceVersion: "104268345"
  uid: ebe3d1fc-c14c-48ef-b7c0-fbcd07abed38
spec:
  clusterIP: 10.43.17.197
  clusterIPs:
  - 10.43.17.197
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-2
    nodePort: 31393
    port: 1248
    protocol: TCP
    targetPort: 1248
  selector:
    app: unit-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
