apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":31859,"protocol":"TCP","serviceName":"fh-validation:unit-2","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-2","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-2","port":1232}],"selector":{"app":"unit-2"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T12:14:34Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-2
  namespace: fh-validation
  resourceVersion: "104267879"
  uid: 479920b3-3a9d-40b5-b2d2-166b96488d62
spec:
  clusterIP: 10.43.188.165
  clusterIPs:
  - 10.43.188.165
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-2
    nodePort: 31859
    port: 1232
    protocol: TCP
    targetPort: 1232
  selector:
    app: unit-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
