apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.10.101"],"port":32008,"protocol":"TCP","serviceName":"fh-validation:unit-2","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sorrir-app","app.kubernetes.io/managed-by":"pulumi"},"name":"unit-2","namespace":"fh-validation"},"spec":{"ports":[{"name":"unit-2","port":1209}],"selector":{"app":"unit-2"},"type":"NodePort"}}
  creationTimestamp: "2022-01-12T12:09:31Z"
  labels:
    app: sorrir-app
    app.kubernetes.io/managed-by: pulumi
  name: unit-2
  namespace: fh-validation
  resourceVersion: "104266840"
  uid: 22840e35-83f1-4968-b331-a60fa1e4d2da
spec:
  clusterIP: 10.43.210.31
  clusterIPs:
  - 10.43.210.31
  externalTrafficPolicy: Cluster
  ports:
  - name: unit-2
    nodePort: 32008
    port: 1209
    protocol: TCP
    targetPort: 1209
  selector:
    app: unit-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
